import json
import pandas as pd
from datetime import datetime

RESPONSE_COLUMNS = [
    "id",
    "originalName",
    "createdDate",
    "updatedDate",
    "wins",
    "losses",
    "draws",
    "finish",
    "archetypeId",
    "sourceUrl",
    "competitionId",
    "competitionName",
    "competitionEndDate",
    "competitionTopN",
    "competitionTypeName",
    "identifier",
    "person",
    "personId",
    "banned",
    "discordId",
    "decklistHash",
    "retired",
    "reviewed",
    "sourceName",
    "archetypeName",
    "name",
    "colors",
    "coloredSymbols",
    "colorSort",
    "legalFormats",
    "omw",
    "seasonId",
    "activeDate",
    "sorted",
    "maindeck",
    "sideboard",
    "canDraw",
    "top8Safe",
    "starsSafe",
    "colorsSafe",
    "personUrl",
    "dateSort",
    "displayDate",
    "showRecord",
    "competitionUrl",
    "url",
    "exportUrl",
    "cmcChartUrl",
    "sourceIsExternal",
    "compRowLen",
    "hasLegalFormat",
    "pdLegal",
    "nonPdLegalFormats",
    "legalIcons",
    "decklist",
    "averageCmc",
    "archetypeUrl",
]


def fill_df(df: pd.DataFrame) -> pd.DataFrame:
    # TODO
    return df
